### ISSUE TITLE
Project rename / reorg

### ISSUE THREAD

**Issue by alexandru** [monifu/monix#91]
Before it is too late, I've decided to change the name for the version 2.0 release. Monifu has a lame English pronunciation (something I didn't realize, as English is not my primary language).

- project to be renamed to Monix
- top level package to `monix`
- website / organization to `monix.io` (I got the domain name)

The question is, should it be renamed? :-)

**Comment by alexandru** [comment]
This was a bad idea, as ideas at 2 a.m. o'clock at Christmas eve tend to be :-P Closing.

**Comment by alexandru** [comment]
Bad idea.

**Comment by alexandru** [comment]
Still deciding whether that's a good or a bad idea.

**Comment by hepin1989** [comment]
@alexandru you have a hard time....are you a libra?lol,what's the mean of `Monifu` in your native language?

**Comment by alexandru** [comment]
@hepin1989 yeap :)

**Comment by alexandru** [comment]
Version `2.0` of Monifu, currently scheduled for the beginning of March, is shaping up to be a major, earth shattering, backwards compatibility breaking version. Given all the refactoring being done, now would be the best time to do it. Also consider that the future RxJava is also renaming its base package from `rx` to `io.reactivex`.

A decision hasn't been made. I'm just leaving this open because the option is still on the table.

**Comment by alexandru** [comment]
It's a done deal. 

- Monix is the name of the project
- `monix` is the top level package
- Monifu and `org.monifu` remains the organization (I own [monifu.org](https://github.com/monifu/monix/issues/91))
- [monix.io](https://monix.io) is the new project website.

**Comment by danpersa** [comment]
good idea to change the name... I was never able to remember the monifu name...

**Comment by alexandru** [comment]
@danpersa thanks, I like the new name very much and I hope I did the right thing.
